<?php

namespace WP_Express_Checkout\Integrations;

use WP_Express_Checkout\Products;
use WP_UnitTestCase;
use WP_UnitTest_Factory_For_Post;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:47.
 *
 * @group integrations
 * @group admin
 *
 * @covers WP_Express_Checkout\Integrations\License_Manager
 */
class License_ManagerAdminTest extends WP_UnitTestCase {

	/**
	 * @var License_Manager
	 */
	protected $object;
	protected $factory;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() :void{
		set_current_screen( 'post.php' );
		$this->object = new License_Manager;
		$this->factory = new WP_UnitTest_Factory_For_Post();
	}

	/**
	 * @covers WP_Express_Checkout\Integrations\License_Manager::admin
	 */
	public function testAdmin() {
		$this->assertTrue( !! has_action( 'add_meta_boxes', array( $this->object, 'add_meta_boxes' ) ) );
		$this->assertTrue( !! has_action( 'wpec_save_product_handler', array( $this->object, 'save_product_handler' ) ) );
	}

	/**
	 * @covers WP_Express_Checkout\Integrations\License_Manager::add_meta_boxes
	 */
	public function testAdd_meta_boxes() {
		$this->assertTrue( empty( $GLOBALS['wp_meta_boxes'][ Products::$products_slug ]['normal']['high']['wpec_slm_meta_box'] ) );
		$this->object->add_meta_boxes();
		$this->assertNotEmpty( $GLOBALS['wp_meta_boxes'][ Products::$products_slug ]['normal']['high']['wpec_slm_meta_box'] );
	}

	/**
	 * @covers WP_Express_Checkout\Integrations\License_Manager::display_meta_box
	 */
	public function testDisplay_meta_box__reflects() {

		$product = $this->factory->create_and_get(
			[
				'post_type' => Products::$products_slug,
			]
		);

		$this->expectOutputRegex( '(wpec_slm_license_enabled)' );
		$this->expectOutputRegex( '(wpec_slm_max_allowed_domains)' );
		$this->expectOutputRegex( '(wpec_slm_date_of_expiry)' );
		$this->object->display_meta_box( $product );
	}

	/**
	 * @covers WP_Express_Checkout\Integrations\License_Manager::save_product_handler
	 */
	public function testSave_product_handler() {
		$product_id = $this->factory->create( [ 'post_type' => Products::$products_slug ] );

		$this->object->save_product_handler( $product_id );
		$this->assertEquals( '', get_post_meta( $product_id, 'wpec_slm_license_enabled', true ) );
		$this->assertEquals( '', get_post_meta( $product_id, 'wpec_slm_max_allowed_domains', true ) );
		$this->assertEquals( '', get_post_meta( $product_id, 'wpec_slm_date_of_expiry', true ) );

		$_POST['wpec_slm_license_enabled'] = 42;
		$_POST['wpec_slm_max_allowed_domains'] = 43;
		$_POST['wpec_slm_date_of_expiry'] = 44;
		$this->object->save_product_handler( $product_id );
		$this->assertEquals( '42', get_post_meta( $product_id, 'wpec_slm_license_enabled', true ) );
		$this->assertEquals( '43', get_post_meta( $product_id, 'wpec_slm_max_allowed_domains', true ) );
		$this->assertEquals( '44', get_post_meta( $product_id, 'wpec_slm_date_of_expiry', true ) );
	}

}
