<?php

namespace WP_Express_Checkout\Products;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-08-18 at 07:03:15.
 *
 * @group products
 *
 * @covers WP_Express_Checkout\Products\One_Time_Product
 */
class One_Time_ProductTest extends \WP_UnitTestCase {

	/**
	 * @var One_Time_Product
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$post = $this->factory->post->create_and_get(
			[
				'post_type' => \WP_Express_Checkout\Products::$products_slug,
				'meta_input' => [
					'wpec_product_type'       => 'one_time',
					'ppec_product_price'      => 10,
				],
			]
		);
		$this->object = new One_Time_Product( $post );
	}

	/**
	 * @covers WP_Express_Checkout\Products\One_Time_Product::get_price
	 */
	public function testGet_price() {
		$this->assertEquals( 10, $this->object->get_price() );
	}

}
