<?php

namespace WP_Express_Checkout\Products;

use WP_Express_Checkout\Products;
use WP_UnitTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-09-03 at 06:59:49.
 *
 * @group products
 *
 * @covers WP_Express_Checkout\Products\Stub_Product
 */
class Stub_ProductTest extends WP_UnitTestCase {

	/**
	 * @var Stub_Product
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$post = $this->factory->post->create_and_get( [ 'post_type' => Products::$products_slug ] );
		$this->object = new Stub_Product( $post );
	}

	/**
	 * @covers WP_Express_Checkout\Products\Stub_Product::get_type
	 */
	public function testGet_type() {
		$this->assertContains( 'is not registered', $this->object->get_type() );
	}

	/**
	 * @covers WP_Express_Checkout\Products\Stub_Product::get_price
	 */
	public function testGet_price() {
		$this->assertEquals( 0, $this->object->get_price() );
	}

}
