<?php

namespace WP_Express_Checkout\Admin;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:13.
 *
 * @covers WP_Express_Checkout\Admin\Admin
 */
class AdminTest extends \WP_UnitTestCase {

	/**
	 * @var Admin
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = Admin::get_instance();
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::get_instance
	 */
	public function testGet_instance() {
		$this->assertInstanceOf( 'WP_Express_Checkout\Admin\Admin', Admin::get_instance() );
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::add_admin_notice
	 * @todo   Implement testAdd_admin_notice().
	 */
	public function testAdd_admin_notice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::show_admin_notices
	 * @todo   Implement testShow_admin_notices().
	 */
	public function testShow_admin_notices() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::enqueue_admin_styles
	 * @todo   Implement testEnqueue_admin_styles().
	 */
	public function testEnqueue_admin_styles() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::enqueue_admin_scripts
	 * @todo   Implement testEnqueue_admin_scripts().
	 */
	public function testEnqueue_admin_scripts() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::add_plugin_admin_menu
	 * @todo   Implement testAdd_plugin_admin_menu().
	 */
	public function testAdd_plugin_admin_menu() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::register_settings
	 * @todo   Implement testRegister_settings().
	 */
	public function testRegister_settings() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::emails_note
	 * @todo   Implement testEmails_note().
	 */
	public function testEmails_note() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::disable_funding_note
	 * @todo   Implement testDisable_funding_note().
	 */
	public function testDisable_funding_note() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::debug_logging_note
	 * @todo   Implement testDebug_logging_note().
	 */
	public function testDebug_logging_note() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::tos_description
	 * @todo   Implement testTos_description().
	 */
	public function testTos_description() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::settings_field_callback
	 * @todo   Implement testSettings_field_callback().
	 */
	public function testSettings_field_callback() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::settings_sanitize_field_callback
	 * @todo   Implement testSettings_sanitize_field_callback().
	 */
	public function testSettings_sanitize_field_callback() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::display_plugin_admin_page
	 * @todo   Implement testDisplay_plugin_admin_page().
	 */
	public function testDisplay_plugin_admin_page() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::add_action_links
	 * @todo   Implement testAdd_action_links().
	 */
	public function testAdd_action_links() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::do_settings_sections
	 * @todo   Implement testDo_settings_sections().
	 */
	public function testDo_settings_sections() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::set_default_editor
	 * @todo   Implement testSet_default_editor().
	 */
	public function testSet_default_editor() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Admin::gen_help_popup
	 * @todo   Implement testGen_help_popup().
	 */
	public function testGen_help_popup() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
