<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:32.
 *
 * @covers WP_Express_Checkout\Order_Summary_Table
 */
class Order_Summary_TableTest extends \WP_UnitTestCase {

	/**
	 * @var Order_Summary_Table
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$post  = $this->factory->post->create_and_get();
		$order = new Order( $post );
		$this->object = new Order_Summary_Table( $order );
	}

	/**
	 * @covers WP_Express_Checkout\Order_Summary_Table::show
	 * @todo   Implement testShow().
	 */
	public function testShow() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
