<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-09-01 at 07:34:55.
 *
 * @group emails
 *
 * @covers WP_Express_Checkout\Emails
 */
class EmailsTest extends \WP_Ajax_UnitTestCase {

	/**
	 * @var \MockPHPMailer
	 */
	protected $mailer;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		parent::setUp();
		require_once WPEC_TESTS_DIR . '/mocks/mock-payment-processor.php';
		reset_phpmailer_instance();
		$this->mailer = $GLOBALS['phpmailer'];
	}

	/**
	 * @covers WP_Express_Checkout\Emails::send_buyer_email
	 */
	public function testSend_buyer_email() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Emails::send_seller_email
	 */
	public function testSend_seller_email() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Emails::send
	 */
	public function testSend() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
