<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:49.
 *
 * @covers WP_Express_Checkout\Payment_Processor_Free
 * @group payments
 * @group ajax
 */
class Payment_Processor_FreeTest extends \WP_Ajax_UnitTestCase {

	/**
	 * @var Payment_Processor_Free
	 */
	protected $object;

	/**
	 * Call a protected method on the processor.
	 *
	 * @param string $method
	 * @param array  $args
	 * @return mixed
	 */
	protected function call_protected_method( $method, array $args = array() ) {
		$reflection = new \ReflectionClass( $this->object );
		$callable   = $reflection->getMethod( $method );
		$callable->setAccessible( true );

		return $callable->invokeArgs( $this->object, $args );
	}

	/**
	 * Create a test coupon post.
	 *
	 * @param array $meta
	 * @return int
	 */
	protected function create_coupon( array $meta ) {
		return $this->factory->post->create( array(
			'post_type'  => 'wpec_coupons',
			'post_title' => 'test coupon',
			'meta_input' => $meta,
		) );
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp():void {
		parent::setUp();
		remove_all_actions( 'wp_ajax_wpec_process_empty_payment' );
		remove_all_actions( 'wp_ajax_nopriv_wpec_process_empty_payment' );
		$this->object = new Payment_Processor_Free;
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor_Free::wpec_process_payment
	 */
	public function testWpec_process_payment() {
		$product_id = $this->factory->post->create( [
			'post_type' => Products::$products_slug,
		] );
		$_POST['wp_ppdg_payment'] = json_decode( file_get_contents( WPEC_TESTS_DIR . '/data/payment-data.json' ), true );
		$_POST['data'] = [
			'id' => 0,
			'product_id' => $product_id,
			'name' => 'test free payment',
			'price'           => 0,
			'currency'        => 'USD',
			'quantity'        => 5,
			'tax'             => 0,
			'shipping'        => 0,
			'shipping_enable' => 1,
			'url'             => 'http://example.com',
			'custom_quantity' => 1,
			'custom_amount'   => 0,
			'product_id'      => $product_id,
			'coupons_enabled' => 1,
			'thank_you_url'   => 'http://example.com/thank_you',
			'total'           => 50,
		];

		set_transient( 'wp-ppdg-test-free-payment', $_POST['data'] );

		$_POST['nonce'] = wp_create_nonce( $_POST['data']['id'] . $product_id );

		try {
			$this->_handleAjax( 'wpec_process_empty_payment' );
		} catch ( \WPAjaxDieContinueException $e ) {
			// We expected this, do nothing.
		}

		$this->assertTrue( isset( $e ) );
		$response = json_decode( $this->_last_response );
		$this->assertNotEmpty( $response->redirect_url );
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor_Free::calculate_free_checkout_total
	 */
	public function testCalculate_free_checkout_total__ignores_coupon_for_other_product() {
		$product_id = $this->factory->post->create( array(
			'post_type' => Products::$products_slug,
		) );
		$other_product_id = $this->factory->post->create( array(
			'post_type' => Products::$products_slug,
		) );

		$this->create_coupon( array(
			'wpec_coupon_code' => 'TEST10',
			'wpec_coupon_active' => 1,
			'wpec_coupon_start_date' => gmdate( 'Y-m-d', current_time( 'timestamp' ) - DAY_IN_SECONDS ),
			'wpec_coupon_exp_date' => 0,
			'wpec_coupon_red_limit' => 0,
			'wpec_coupon_red_count' => 0,
			'wpec_coupon_discount' => 10,
			'wpec_coupon_discount_type' => 'fixed',
			'wpec_coupon_only_for_allowed_products' => 1,
			'wpec_coupon_allowed_products' => array( $product_id ),
		) );

		$total = $this->call_protected_method( 'calculate_free_checkout_total', array( 20, 1, 0, 0, $other_product_id, array( 'couponCode' => 'TEST10' ) ) );

		$this->assertSame( 20.0, (float) $total );
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor_Free::calculate_free_checkout_total
	 */
	public function testCalculate_free_checkout_total__clamps_negative_total_to_zero() {
		$product_id = $this->factory->post->create( array(
			'post_type' => Products::$products_slug,
		) );

		$this->create_coupon( array(
			'wpec_coupon_code' => 'BIGFIXED',
			'wpec_coupon_active' => 1,
			'wpec_coupon_start_date' => gmdate( 'Y-m-d', current_time( 'timestamp' ) - DAY_IN_SECONDS ),
			'wpec_coupon_exp_date' => 0,
			'wpec_coupon_red_limit' => 0,
			'wpec_coupon_red_count' => 0,
			'wpec_coupon_discount' => 25,
			'wpec_coupon_discount_type' => 'fixed',
			'wpec_coupon_only_for_allowed_products' => 0,
			'wpec_coupon_allowed_products' => array(),
		) );

		$total = $this->call_protected_method( 'calculate_free_checkout_total', array( 10, 1, 0, 0, $product_id, array( 'couponCode' => 'BIGFIXED' ) ) );

		$this->assertSame( 0.0, (float) $total );
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor_Free::calculate_free_checkout_total
	 */
	public function testCalculate_free_checkout_total__multiplies_variation_price_by_quantity() {
		$product_id = $this->factory->post->create( array(
			'post_type'  => Products::$products_slug,
			'meta_input' => array(
				'wpec_variations_groups' => array( 'Color' ),
				'wpec_variations_names'  => array( array( 'Blue' ) ),
				'wpec_variations_prices' => array( array( 2 ) ),
				'wpec_variations_urls'   => array( array( '' ) ),
				'wpec_variations_opts'   => array( array( 0 ) ),
			),
		) );

		$total = $this->call_protected_method(
			'calculate_free_checkout_total',
			array(
				0,
				3,
				0,
				0,
				$product_id,
				array(
					'variations' => array(
						'applied' => array( 0 ),
					),
				)
			)
		);

		$this->assertSame( 6.0, (float) $total );
	}

}
