<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:47.
 */
class IntegrationsTest extends \WP_UnitTestCase {

	/**
	 * @var Integrations
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Integrations;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Integrations::handle_emember_signup
	 * @todo   Implement testHandle_emember_signup().
	 */
	public function testHandle_emember_signup() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
