<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:34.
 *
 * @covers WP_Express_Checkout\Payment_Processor
 */
class Payment_ProcessorTest extends \WP_UnitTestCase {

	/**
	 * @var Payment_Processor
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Payment_Processor;
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor::get_instance
	 */
	public function testGet_instance() {
		$this->assertInstanceOf( 'WP_Express_Checkout\Payment_Processor', Payment_Processor::get_instance() );
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor::wpec_process_payment
	 * @todo   Implement testWpec_process_payment().
	 */
	public function testWpec_process_payment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor::is_custom_amount
	 */
	public function testIs_custom_amount() {
		$this->assertTrue( $this->object->is_custom_amount( 1 ) );
		$this->assertFalse( $this->object->is_custom_amount( 0 ) );
	}

}
