<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:29.
 */
class View_DownloadsTest extends \WP_UnitTestCase {

	/**
	 * @var View_Downloads
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new View_Downloads;
	}

	/**
	 * @covers WP_Express_Checkout\View_Downloads::get_instance
	 */
	public function testGet_instance() {
		$this->assertInstanceOf( 'WP_Express_Checkout\View_Downloads', View_Downloads::get_instance() );
	}

	/**
	 * @covers WP_Express_Checkout\View_Downloads::get_download_url
	 * @todo   Implement testGet_download_url().
	 */
	public function testGet_download_url() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\View_Downloads::get_order_downloads_list
	 * @todo   Implement testGet_order_downloads_list().
	 */
	public function testGet_order_downloads_list() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
