<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:44.
 */
class UtilsTest extends \WP_UnitTestCase {

	/**
	 * @var Utils
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Utils;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Utils::price_format
	 * @todo   Implement testPrice_format().
	 */
	public function testPrice_format() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::price_modifier
	 * @todo   Implement testPrice_modifier().
	 */
	public function testPrice_modifier() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::get_tax_amount
	 * @todo   Implement testGet_tax_amount().
	 */
	public function testGet_tax_amount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::round_price
	 * @todo   Implement testRound_price().
	 */
	public function testRound_price() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::apply_tax
	 * @todo   Implement testApply_tax().
	 */
	public function testApply_tax() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::apply_shipping
	 * @todo   Implement testApply_shipping().
	 */
	public function testApply_shipping() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::replace_dynamic_order_tags
	 * @todo   Implement testReplace_dynamic_order_tags().
	 */
	public function testReplace_dynamic_order_tags() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::apply_dynamic_tags
	 * @todo   Implement testApply_dynamic_tags().
	 */
	public function testApply_dynamic_tags() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::get_product_details
	 * @todo   Implement testGet_product_details().
	 */
	public function testGet_product_details() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::redirect_to_url
	 * @todo   Implement testRedirect_to_url().
	 */
	public function testRedirect_to_url() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Utils::get_countries_untranslated
	 * @todo   Implement testGet_countries_untranslated().
	 */
	public function testGet_countries_untranslated() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
