<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:57.
 */
class ProductsTest extends \WP_UnitTestCase {

	/**
	 * @var Products
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Products;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Products::get_instance
	 * @todo   Implement testGet_instance().
	 */
	public function testGet_instance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Products::register_post_type
	 * @todo   Implement testRegister_post_type().
	 */
	public function testRegister_post_type() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Products::post_updated_messages
	 * @todo   Implement testPost_updated_messages().
	 */
	public function testPost_updated_messages() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Products::manage_columns
	 * @todo   Implement testManage_columns().
	 */
	public function testManage_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Products::manage_custom_columns
	 * @todo   Implement testManage_custom_columns().
	 */
	public function testManage_custom_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Products::manage_sortable_columns
	 * @todo   Implement testManage_sortable_columns().
	 */
	public function testManage_sortable_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
