<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:49.
 */
class Payment_Processor_FreeTest extends \WP_UnitTestCase {

	/**
	 * @var Payment_Processor_Free
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Payment_Processor_Free;
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor_Free::wpec_process_payment
	 * @todo   Implement testWpec_process_payment().
	 */
	public function testWpec_process_payment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
