<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:36.
 */
class OrderTest extends \WP_UnitTestCase {

	/**
	 * @var Order
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$post = $this->factory->post->create_and_get();
		$this->object = new Order( $post );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Order::get_info
	 * @todo   Implement testGet_info().
	 */
	public function testGet_info() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_id
	 * @todo   Implement testGet_id().
	 */
	public function testGet_id() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_description
	 * @todo   Implement testGet_description().
	 */
	public function testGet_description() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::set_description
	 * @todo   Implement testSet_description().
	 */
	public function testSet_description() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::add_item
	 * @todo   Implement testAdd_item().
	 */
	public function testAdd_item() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::remove_item
	 * @todo   Implement testRemove_item().
	 */
	public function testRemove_item() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_item
	 * @todo   Implement testGet_item().
	 */
	public function testGet_item() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_items
	 * @todo   Implement testGet_items().
	 */
	public function testGet_items() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_total
	 * @todo   Implement testGet_total().
	 */
	public function testGet_total() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::set_currency
	 * @todo   Implement testSet_currency().
	 */
	public function testSet_currency() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_currency
	 * @todo   Implement testGet_currency().
	 */
	public function testGet_currency() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_status
	 * @todo   Implement testGet_status().
	 */
	public function testGet_status() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_display_status
	 * @todo   Implement testGet_display_status().
	 */
	public function testGet_display_status() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::set_status
	 * @todo   Implement testSet_status().
	 */
	public function testSet_status() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::set_author
	 * @todo   Implement testSet_author().
	 */
	public function testSet_author() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::set_author_email
	 * @todo   Implement testSet_author_email().
	 */
	public function testSet_author_email() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_author
	 * @todo   Implement testGet_author().
	 */
	public function testGet_author() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_ip_address
	 * @todo   Implement testGet_ip_address().
	 */
	public function testGet_ip_address() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_return_url
	 * @todo   Implement testGet_return_url().
	 */
	public function testGet_return_url() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_cancel_url
	 * @todo   Implement testGet_cancel_url().
	 */
	public function testGet_cancel_url() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_parent
	 * @todo   Implement testGet_parent().
	 */
	public function testGet_parent() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_resource_id
	 * @todo   Implement testGet_resource_id().
	 */
	public function testGet_resource_id() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::set_resource_id
	 * @todo   Implement testSet_resource_id().
	 */
	public function testSet_resource_id() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::add_data
	 * @todo   Implement testAdd_data().
	 */
	public function testAdd_data() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_data
	 * @todo   Implement testGet_data().
	 */
	public function testGet_data() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Order::get_url
	 * @todo   Implement testGet_url().
	 */
	public function testGet_url() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
