<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:47.
 *
 * @group integrations
 *
 * @covers WP_Express_Checkout\Integrations
 */
class IntegrationsTest extends \WP_UnitTestCase {

	/**
	 * @var Integrations
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Integrations;
	}

	public function test_test () {
		$this->assertTrue( true );
	}

}
