<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:10.
 *
 * @covers WP_Express_Checkout\Post_Type_Content_Handler
 */
class Post_Type_Content_HandlerTest extends \WP_UnitTestCase {

	/**
	 * @var Post_Type_Content_Handler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Post_Type_Content_Handler;
	}

	/**
	 * @covers WP_Express_Checkout\Post_Type_Content_Handler::get_instance
	 */
	public function testGet_instance() {
		$this->assertInstanceOf( 'WP_Express_Checkout\Post_Type_Content_Handler', Post_Type_Content_Handler::get_instance() );
	}

	/**
	 * @covers WP_Express_Checkout\Post_Type_Content_Handler::filter_post_type_content
	 * @todo   Implement testFilter_post_type_content().
	 */
	public function testFilter_post_type_content() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
