<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:39.
 *
 * @covers WP_Express_Checkout\Init
 */
class InitTest extends \WP_UnitTestCase {

	/**
	 * @var Init
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Init;
	}

	/**
	 * @covers WP_Express_Checkout\Init::do_init_time_tasks
	 * @todo   Implement testDo_init_time_tasks().
	 */
	public function testDo_init_time_tasks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Init::wpec_handle_reset_log
	 * @todo   Implement testWpec_handle_reset_log().
	 */
	public function testWpec_handle_reset_log() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Init::handle_view_log_action
	 * @todo   Implement testHandle_view_log_action().
	 */
	public function testHandle_view_log_action() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
