<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:42.
 */
class CouponsTest extends \WP_UnitTestCase {

	/**
	 * @var Coupons
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Coupons;
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::get_coupon
	 * @todo   Implement testGet_coupon().
	 */
	public function testGet_coupon() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::is_coupon_allowed_for_product
	 * @todo   Implement testIs_coupon_allowed_for_product().
	 */
	public function testIs_coupon_allowed_for_product() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::frontend_check_coupon
	 * @todo   Implement testFrontend_check_coupon().
	 */
	public function testFrontend_check_coupon() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::init_handler
	 * @todo   Implement testInit_handler().
	 */
	public function testInit_handler() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::add_menu
	 * @todo   Implement testAdd_menu().
	 */
	public function testAdd_menu() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::save_settings
	 * @todo   Implement testSave_settings().
	 */
	public function testSave_settings() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::display_coupons_menu_page
	 * @todo   Implement testDisplay_coupons_menu_page().
	 */
	public function testDisplay_coupons_menu_page() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::display_coupon_add_edit_page
	 * @todo   Implement testDisplay_coupon_add_edit_page().
	 */
	public function testDisplay_coupon_add_edit_page() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::delete_coupon
	 * @todo   Implement testDelete_coupon().
	 */
	public function testDelete_coupon() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::save_coupon
	 * @todo   Implement testSave_coupon().
	 */
	public function testSave_coupon() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::add_discount_to_order
	 * @todo   Implement testAdd_discount_to_order().
	 */
	public function testAdd_discount_to_order() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Coupons::redeem_coupon
	 * @todo   Implement testRedeem_coupon().
	 */
	public function testRedeem_coupon() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
