<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:00.
 *
 * @covers WP_Express_Checkout\Variations
 */
class VariationsTest extends \WP_UnitTestCase {

	/**
	 * @var Variations
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp():void {
		$this->object = new Variations( 0 );
	}

	/**
	 * @covers WP_Express_Checkout\Variations::get_variation
	 * @todo   Implement testGet_variation().
	 */
	public function testGet_variation() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Variations::init
	 * @todo   Implement testInit().
	 */
	public function testInit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Variations::add_variations_to_order
	 * @todo   Implement testAdd_variations_to_order().
	 */
	public function testAdd_variations_to_order() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
