<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:34.
 */
class Payment_ProcessorTest extends \WP_UnitTestCase {

	/**
	 * @var Payment_Processor
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Payment_Processor;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor::get_instance
	 * @todo   Implement testGet_instance().
	 */
	public function testGet_instance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor::wpec_process_payment
	 * @todo   Implement testWpec_process_payment().
	 */
	public function testWpec_process_payment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Payment_Processor::is_custom_amount
	 * @todo   Implement testIs_custom_amount().
	 */
	public function testIs_custom_amount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
