<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:03.
 */
class OrdersTest extends \WP_UnitTestCase {

	/**
	 * @var Orders
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Orders;
	}

	/**
	 * @covers WP_Express_Checkout\Orders::register_post_type
	 */
	public function testRegister_post_type() {
		unregister_post_type( Orders::PTYPE );
		$this->assertNull( get_post_type_object( Orders::PTYPE ) );
		$this->object->register_post_type();
		$this->assertInstanceOf( 'WP_Post_Type', get_post_type_object( Orders::PTYPE ) );
	}

	/**
	 * @covers WP_Express_Checkout\Orders::get_instance
	 */
	public function testGet_instance() {
		$this->assertInstanceOf( 'WP_Express_Checkout\Orders', Orders::get_instance() );
	}

	/**
	 * @covers WP_Express_Checkout\Orders::create
	 * @todo   Implement testCreate().
	 */
	public function testCreate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Orders::retrieve
	 * @todo   Implement testRetrieve().
	 */
	public function testRetrieve() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
