<?php

namespace WP_Express_Checkout\Debug;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:05.
 *
 * @covers WP_Express_Checkout\Debug\Logger
 */
class LoggerTest extends \WP_UnitTestCase {

	/**
	 * @var Logger
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() :void{
		$this->object = new Logger;
	}

	/**
	 * @covers WP_Express_Checkout\Debug\Logger::log
	 * @todo   Implement testLog().
	 */
	public function testLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Debug\Logger::reset_log
	 * @todo   Implement testReset_log().
	 */
	public function testReset_log() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
