<?php

namespace WP_Express_Checkout;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:03.
 */
class OrdersTest extends \WP_UnitTestCase {

	/**
	 * @var Orders
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Orders;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Orders::register_post_type
	 * @todo   Implement testRegister_post_type().
	 */
	public function testRegister_post_type() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Orders::get_instance
	 * @todo   Implement testGet_instance().
	 */
	public function testGet_instance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Orders::create
	 * @todo   Implement testCreate().
	 */
	public function testCreate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Orders::retrieve
	 * @todo   Implement testRetrieve().
	 */
	public function testRetrieve() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
