<?php

namespace WP_Express_Checkout\PayPal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:52.
 *
 * @group paypal-client
 *
 * @covers WP_Express_Checkout\PayPal\Client
 */
class ClientTest extends \WP_UnitTestCase {

	/**
	 * @var Client
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Client;
	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Client::client
	 */
	public function testClient() {
		$client = Client::client();
		$this->assertInstanceOf( 'PayPalCheckoutSdk\Core\PayPalHttpClient', $client );
	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Client::environment
	 */
	public function testEnvironment() {
		$live_env = Client::environment( 'live' );
		$test_env = Client::environment( 'test' );

		$this->assertInstanceOf( 'PayPalCheckoutSdk\Core\ProductionEnvironment', $live_env );
		$this->assertInstanceOf( 'PayPalCheckoutSdk\Core\SandboxEnvironment', $test_env );
	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Client::environment
	 */
	public function testEnvironment__default() {
		$options = get_option( 'ppdg-settings' );
		$options['is_live'] = 1;
		update_option( 'ppdg-settings', $options );

		$live_env = Client::environment();
		$this->assertInstanceOf( 'PayPalCheckoutSdk\Core\ProductionEnvironment', $live_env );

		$options = get_option( 'ppdg-settings' );
		$options['is_live'] = 0;
		update_option( 'ppdg-settings', $options );

		$test_env = Client::environment( 'test' );
		$this->assertInstanceOf( 'PayPalCheckoutSdk\Core\SandboxEnvironment', $test_env );
	}

}
