<?php

namespace WP_Express_Checkout\PayPal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:55.
 */
class RequestTest extends \WP_UnitTestCase {

	/**
	 * @var Request
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Request( '/v1/catalogs/products', 'GET' );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Request::prefer
	 * @todo   Implement testPrefer().
	 */
	public function testPrefer() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
