<?php

namespace WP_Express_Checkout\PayPal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:55.
 *
 * @group paypal-client
 *
 * @covers WP_Express_Checkout\PayPal\Request
 */
class RequestTest extends \WP_UnitTestCase {

	/**
	 * @var Request
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp():void {
		$this->object = new Request( '/v1/catalogs/products', 'GET' );
	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Request::prefer
	 */
	public function testPrefer() {
		$this->object->prefer( 'dummy' );
		$this->assertEquals( 'dummy', $this->object->headers['Prefer'] );
	}

}
