<?php

namespace WP_Express_Checkout\PayPal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:52:52.
 */
class ClientTest extends \WP_UnitTestCase {

	/**
	 * @var Client
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Client;
	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Client::client
	 * @todo   Implement testClient().
	 */
	public function testClient() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\PayPal\Client::environment
	 * @todo   Implement testEnvironment().
	 */
	public function testEnvironment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
