<?php

namespace WP_Express_Checkout\Admin;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:19.
 *
 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes
 */
class Products_Meta_BoxesTest extends \WP_UnitTestCase {

	/**
	 * @var Products_Meta_Boxes
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Products_Meta_Boxes;
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::add_meta_boxes
	 * @todo   Implement testAdd_meta_boxes().
	 */
	public function testAdd_meta_boxes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_description_meta_box
	 * @todo   Implement testDisplay_description_meta_box().
	 */
	public function testDisplay_description_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_price_meta_box
	 * @todo   Implement testDisplay_price_meta_box().
	 */
	public function testDisplay_price_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_variations_meta_box
	 * @todo   Implement testDisplay_variations_meta_box().
	 */
	public function testDisplay_variations_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_quantity_meta_box
	 * @todo   Implement testDisplay_quantity_meta_box().
	 */
	public function testDisplay_quantity_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_shipping_tax_meta_box
	 * @todo   Implement testDisplay_shipping_tax_meta_box().
	 */
	public function testDisplay_shipping_tax_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_upload_meta_box
	 * @todo   Implement testDisplay_upload_meta_box().
	 */
	public function testDisplay_upload_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_thumbnail_meta_box
	 * @todo   Implement testDisplay_thumbnail_meta_box().
	 */
	public function testDisplay_thumbnail_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_thankyou_page_meta_box
	 * @todo   Implement testDisplay_thankyou_page_meta_box().
	 */
	public function testDisplay_thankyou_page_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_shortcode_meta_box
	 * @todo   Implement testDisplay_shortcode_meta_box().
	 */
	public function testDisplay_shortcode_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_appearance_meta_box
	 * @todo   Implement testDisplay_appearance_meta_box().
	 */
	public function testDisplay_appearance_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_coupons_meta_box
	 * @todo   Implement testDisplay_coupons_meta_box().
	 */
	public function testDisplay_coupons_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::display_emember_meta_box
	 * @todo   Implement testDisplay_emember_meta_box().
	 */
	public function testDisplay_emember_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Products_Meta_Boxes::save_product_handler
	 * @todo   Implement testSave_product_handler().
	 */
	public function testSave_product_handler() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Products::post_updated_messages
	 * @todo   Implement testPost_updated_messages().
	 */
	public function testPost_updated_messages() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
