<?php

namespace WP_Express_Checkout\Admin;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:27.
 *
 * @covers WP_Express_Checkout\Admin\Coupons_List
 */
class Coupons_ListTest extends \WP_UnitTestCase {

	/**
	 * @var Coupons_List
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Coupons_List( [ 'screen' => 'front' ] );
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Coupons_List::prepare_items
	 * @todo   Implement testPrepare_items().
	 */
	public function testPrepare_items() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Coupons_List::get_columns
	 * @todo   Implement testGet_columns().
	 */
	public function testGet_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Coupons_List::column_default
	 * @todo   Implement testColumn_default().
	 */
	public function testColumn_default() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Coupons_List::get_sortable_columns
	 * @todo   Implement testGet_sortable_columns().
	 */
	public function testGet_sortable_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
