<?php

namespace WP_Express_Checkout\Admin;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:24.
 */
class Orders_ListTest extends \WP_UnitTestCase {

	/**
	 * @var Orders_List
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Orders_List;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {

	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_List::init
	 * @todo   Implement testInit().
	 */
	public function testInit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_List::order_manage_columns
	 * @todo   Implement testOrder_manage_columns().
	 */
	public function testOrder_manage_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_List::order_manage_sortable_columns
	 * @todo   Implement testOrder_manage_sortable_columns().
	 */
	public function testOrder_manage_sortable_columns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_List::order_add_column_data
	 * @todo   Implement testOrder_add_column_data().
	 */
	public function testOrder_add_column_data() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_List::set_search_term
	 * @todo   Implement testSet_search_term().
	 */
	public function testSet_search_term() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_List::manage_search_sort_queries
	 * @todo   Implement testManage_search_sort_queries().
	 */
	public function testManage_search_sort_queries() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
