<?php

namespace WP_Express_Checkout\Admin;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-06-28 at 07:53:21.
 *
 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes
 */
class Orders_Meta_BoxesTest extends \WP_UnitTestCase {

	/**
	 * @var Orders_Meta_Boxes
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->object = new Orders_Meta_Boxes;
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes::add_meta_boxes
	 * @todo   Implement testAdd_meta_boxes().
	 */
	public function testAdd_meta_boxes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes::display_summary_meta_box
	 * @todo   Implement testDisplay_summary_meta_box().
	 */
	public function testDisplay_summary_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes::display_status_meta_box
	 * @todo   Implement testDisplay_status_meta_box().
	 */
	public function testDisplay_status_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes::display_author_meta_box
	 * @todo   Implement testDisplay_author_meta_box().
	 */
	public function testDisplay_author_meta_box() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes::save
	 * @todo   Implement testSave().
	 */
	public function testSave() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers WP_Express_Checkout\Admin\Orders_Meta_Boxes::remove_meta_boxes
	 * @todo   Implement testRemove_meta_boxes().
	 */
	public function testRemove_meta_boxes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
