<?php

namespace WP_Express_Checkout\Integrations;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-09-03 at 06:59:52.
 *
 * @group integrations
 * @group woocommerce
 *
 * @covers WP_Express_Checkout\Integrations\WooCommerce_Payment_Processor
 */
class WooCommerce_Payment_ProcessorTest extends \WP_UnitTestCase {

	/**
	 * @var WooCommerce_Payment_Processor
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp():void {
		$this->object = new WooCommerce_Payment_Processor;
	}

	/**
	 * @covers WP_Express_Checkout\Integrations\WooCommerce_Payment_Processor::wpec_process_payment
	 * @todo   Implement testWpec_process_payment().
	 */
	public function testWpec_process_payment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
