<?php

namespace WP_Express_Checkout\Blocks;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-07-14 at 07:00:27.
 *
 * @group blocks
 */
class Dynamic_Block_Test extends Dynamic_Block {

	protected $name = 'wp-express-checkout/dynamic-block-test';


	public function render_callback( $atts, $content ) {
		return true;
	}

}
